name: Cache Node and NPM Dependencies
description: This action allows to cache both Node and NPM dependencies based on the package-lock.json file.
inputs:
  node-version:
    description: NodeJS version to use
    required: false
    default: 20.x
  working-dir:
    description: The working directory of the application
    default: .
  target-env:
    description: '"dev" or "prod". Controls whether dev dependencies are installed'
    default: dev
outputs:
  installed-deps:
    description: Whether dependencies were installed or not
    value: ${{ steps.cache.outputs.cache-hit != 'true' }}
runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{inputs.node-version}}
      uses: actions/setup-node@v6
      with:
        node-version: ${{inputs.node-version}}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        key: ${{inputs.target-env}}-${{ hashFiles(format('{0}/package-lock.json', inputs.working-dir)) }}s
        path: ${{inputs.working-dir}}/package-lock.json
    - name: Install dependencies
      shell: sh
      working-directory: ${{inputs.working-dir}}
      if: steps.cache.outputs.cache-hit != 'true'
      run: ${{inputs.target-env == 'dev' && 'npm ci' || 'npm ci --omit=dev'}}
