name: Cache Node and NPM Dependencies
description: This action allows to cache both Node and NPM dependencies based on the package-lock.json file.
inputs:
  node-version:
    description: NodeJS version to use
    required: false
    default: 20.x
  working-dir:
    description: The working directory of the application
    default: .
runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{inputs.node-version}}
      uses: actions/setup-node@v6
      with:
        node-version: ${{inputs.node-version}}
    - name: Calculate cache key
      id: cache-key
      shell: sh
      run: echo "CACHE_KEY=${{hashFiles(inputs.working-dir+"/package-lock.json")}}"
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        key: ${{steps.cache-key.outputs.CACHE_KEY}}
        path: ${{inputs.working-dir}}/package-lock.json
    - name: Install dependencies
      shell: sh
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      working-directory: ${{inputs.working-dir}}
