name: 04 - Using Actions
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
        working-directory: 04-using-actions/react-app
      - name: Run unit tests
        run: npm test
        working-directory: 04-using-actions/react-app
