name: 13 - Using Caching
on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: Whether to execute cache step
                type: boolean
                default: true

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/react-app
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v6
              with:
                  node-version: 20.x
            - name: Install dependencies
              run: npm ci
            - name: Testing
              run: npm test
            - name: Building
              run: npm run build
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod"
