name: 17 - 1 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions - Composite | env - ${{ inputs.target-env }}
env:
  working-directory: 17-custom-actions/react-app
on:
  workflow_dispatch:
    inputs:
      target-env:
        description: Target env
        required: true
        type: choice
        options:
          - dev
          - prod
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node and NPM Dependencies
        id: setup-deps
        uses: ./.github/actions/composite-cache-deps
        with:
          working-dir: ${{ env.working-directory }}
          target-env: ${{inputs.target-env}}
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Print setup deps output
        run: |
          echo "Installed dependencies: ${{ steps.setup-deps.outputs.installed-deps }}"
