name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS
on: workflow_dispatch
jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check for dependency updates
        uses: ./.github/actions/js-dependency-update
        with:
          base-branch: main
          target-branch: main
          working-dir: 17-custom-actions/react-app
          debug: true
          gh-token: ${{ github.token }}
