name: 17 - 3 - Custom Actions - Docker
on:
  workflow_dispatch:
    inputs:
      url:
        type: choice
        options:
          - https://wwww.google.com
          - https://unreachable-url.com
        description: URL
        default: https://wwww.google.com
      max_trials:
        description: Maximum trials until action fails
        type: number
        default: 5

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ github.event.inputs.url }}
          max_trials: ${{ github.event.inputs.max_trials }}
