name: 17 - 3 - Custom Actions - Docker
on:
  workflow_dispatch:
    inputs:
      url:
        description: URL
        default: https://wwww.google.com

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/docker-ping-url
